spring:
  application:
    name: discovery-server
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  server:
    enable-self-preservation: false
    max-threads-for-peer-replication: 0

management:
    security:
        enabled: false
        


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 6000


ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000